### ISSUE TITLE
String expansion regression

### ISSUE THREAD

**Issue by cfenell** [danielk333/pypaper#2]
Hi,

last correction has an interesting effect

pypaper
...
  File "/home/fredrik/.local/lib/python3.7/site-packages/pypaper/bib.py", line 68, in rename_bibtex
    author_str = entry['publisher'].replace(' ', '_').strip()
AttributeError: 'BibDataStringExpression' object has no attribute 'replace'
...
(Pdb) entry['publisher']
BibDataStringExpression([BibDataString('afgl')])

The entry is the first one in the bibtex file
(Pdb) entry
{'editor': 'Adolph, S. J.', 'year': '1985', 'publisher': BibDataStringExpression([BibDataString('afgl')]), 'title': 'Handbook of {G}eophysics and the {S}pace\n{E}nvironment', 'ENTRYTYPE': 'book', 'ID': 'adolph1985afgl'}

**Comment by cfenell** [comment]
And it should expand like this
@STRING{afgl	= "Air Force Geophysics Laboratory, United States Air Force" }

**Comment by danielk333** [comment]
Thanks! This is exactly the kind of testing i need!

Anyway, I know where this is coming from, since the book entry does not have an author, it tries the next best thing and use the publisher instead to id-the entry. I just need to make sure that it always resolves the string before doing string operations inside the id-function

**Comment by danielk333** [comment]
Did this resolve the error? If it didnt, could you send me the bibtex file so i can experiment some more?
